services:
    shapecode_setup.command.setup:
        class: Shapecode\Bundle\SetupBundle\Command\SetupCommand
        tags:
            -  { name: console.command }

    shapecode_setup.reference_manager:
        class: Shapecode\Bundle\SetupBundle\Setup\ReferenceManager
        arguments: ["@doctrine"]

    shapecode_setup.abstrat_setup:
        abstract: true
        calls:
            - ['setRegistry', ['@doctrine']]
            - ['setReferenceManager', ['@shapecode_setup.reference_manager']]
