services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shapecode\Bundle\SetupBundle\Command\SetupCommand: ~
    Shapecode\Bundle\SetupBundle\Setup\ReferenceManager: ~
    Shapecode\Bundle\SetupBundle\Setup\ReferenceManagerInterface: '@Shapecode\Bundle\SetupBundle\Setup\ReferenceManager'
